### ISSUE TITLE
LinkedIn videos are not rewritten in HTML causing error in video playback

### ISSUE THREAD

**Issue by tsemachh** [webrecorder/archiveweb.page#124]
Hi
When recording LinkedIn post with video , video is captured well in the WACZ but it's not playable on replay.web page.
Example:
[WACZ](https://wacz-archives.s3.eu-west-1.amazonaws.com/dvora/12_14_2022/09_11_08.wacz)
[Recorded  URL](https://www.linkedin.com/posts/avi-lewis_%D7%A7%D7%99%D7%A6%D7%95%D7%A8%D7%99-%D7%93%D7%A8%D7%9A-%D7%A0%D7%97%D7%9E%D7%93%D7%99%D7%9D-%D7%95%D7%A4%D7%95%D7%A0%D7%A7%D7%A6%D7%99%D7%95%D7%AA-%D7%A9%D7%99%D7%9E%D7%95%D7%A9%D7%99%D7%95%D7%AA-%D7%91%D7%90%D7%A7%D7%A1%D7%9C-ugcPost-7008356629414883329-JR5X/?utm_source=share&utm_medium=member_desktop)
In the replayed HTML I see:
"progressiveStreams":[{"streamingLocations":[{"url":"https://dms.licdn.com/playlist/C4D05AQFja8dcVjslxA/mp4-720p-30fp-crf28/0/1670922455446?e=1671544800&v=beta&t=R30K4LucwsTvuFIUTlVml40gDYR2VjZS_9HXRyhfUmM"

And indeed in the WACZ I see the video is captured OK:
[https://dms.licdn.com/playlist/C4D05AQFja8dcVjslxA/mp4-720p-30fp-crf28/0/1670922455446?e=1671544800&v=beta&t=R30K4LucwsTvuFIUTlVml40gDYR2VjZS_9HXRyhfUmM](https://replayweb.page/?source=file%3A%2F%2Fmy-web-archive%20(13).wacz#view=resources&url=https%3A%2F%2Fdms.licdn.com%2Fplaylist%2FC4D05AQFja8dcVjslxA%2Fmp4-720p-30fp-crf28%2F0%2F1670922455446%3Fe%3D1671544800%26v%3Dbeta%26t%3DR30K4LucwsTvuFIUTlVml40gDYR2VjZS_9HXRyhfUmM&ts=20221213135518)

I think the WABAC rewriter doesn't rewrite this URL causing it not to be playable in the replay.web page
(BTW - In the extension which doesn't care about security policy it's playing the original well but this doesn't help)

Thank you
Tsemach

**Comment by ikreymer** [comment]
> Hi When recording LinkedIn post with video , video is captured well in the WACZ but it's not playable on replay.web page. Example: [WACZ](https://wacz-archives.s3.eu-west-1.amazonaws.com/dvora/12_14_2022/09_11_08.wacz) [Recorded URL](https://www.linkedin.com/posts/avi-lewis_%D7%A7%D7%99%D7%A6%D7%95%D7%A8%D7%99-

Thanks, should have a fix for this, involved a couple of issues in (wombat.js and wabac.js) that caused the live leak,
which replayweb.page prevents.

> I think the WABAC rewriter doesn't rewrite this URL causing it not to be playable in the replay.web page (BTW - In the extension which doesn't care about security policy it's playing the original well but this doesn't help)
> 

> So the impact on the extension user will be misleading: he (she) will thinks he captured the whole post including the video since it plays on the extension window but actually it plays from the original site and not from the archive so it may disappear if the original site remove it...

Yes, this is a known issue, unfortunately, we have to disable the CSP policy in the extension, because otherwise the page will not load at all, because Chrome as of a few versions ago, enforces a CSP policy where regular replay doesn't work (eg. blocking eval, inline scripts). The only way to make it work at all is to disable CSP when loading in the extension. This is not at all ideal, but that's the best we can do for now.

**Comment by ikreymer** [comment]
Replay fixed in replayweb.page 1.7.9
