### ISSUE TITLE
Instagram reels cannot be played in extension and in replayweb.page

### ISSUE THREAD

**Issue by tsemachh** [webrecorder/archiveweb.page#125]
Hi
Spent few hours trying to figure out why recording Instagram reels are not playable.
Must emphasize that some reels are working , didn't find the pattern when it's playable and when not.
**Next reels worked:**
Not logged in to instagram - [https://www.instagram.com/reel/CJ_lk8Xn6uz](https://www.instagram.com/reel/CJ_lk8Xn6uz)
Logged In - [https://www.instagram.com/reel/CXgbY9zAv_i/](https://www.instagram.com/reel/CXgbY9zAv_i/)
**Next reels playback didn't work:**
Logged in - [https://www.instagram.com/reel/Cd2fjy9oRgL/](https://www.instagram.com/reel/Cd2fjy9oRgL/)
Logged in - [https://www.instagram.com/reel/CYnzKG_K46e/](https://www.instagram.com/reel/CYnzKG_K46e/)
Logged in - [https://www.instagram.com/reel/CmE15cfrqlV/](https://www.instagram.com/reel/CmE15cfrqlV/)

Now - from what I checked in the WACZ - network capture seems to be fine I think the video comes in chunks using API with different parameters for each chunk like:
&bytestart=788&byteend=1023
In the WACZ I see all requests as in the network tab , but still the video is not played , so it may be something related to rewrite of the page
I would be happy to know how we debug such cases
I put the samples in [this](https://wacz-archives.s3.amazonaws.com/samples/InstagramReelsNotWorking.wacz) wacz

**Comment by ikreymer** [comment]
The issue in this case was that Instagram changed something, and the code that forced loading on non-DASH videos was no longer working. With the fix in wabac.js, this should start working again, and will be in the next release.
In general, Instagram uses DASH manifests so there are additional things that could be done to force consistent loading.

**Comment by ikreymer** [comment]
This should now be working, but will require re-recording previously recorded reels, with the new rules.
Also, potential issue where the reel page loads the profile page occasionally, but that seems to be a separate issue.
The byte-range loading should not be happening with the new rules (until something breaks again..)
