### ISSUE TITLE
Vimeo video can't be recorded on the extension

### ISSUE THREAD

**Issue by tsemachh** [webrecorder/archiveweb.page#126]
Hi
When trying to record vimeo video I get errors either I am logged in or not.
Example video:
[https://vimeo.com/773140243
](https://vimeo.com/773140243
)Errors in console:
Some internal to vimeo player - I can't understand much as source map is no present there.
And also another error:(Which is not the cause as also in our extension without the flash we have same issue)
(Maybe leave the flash support only for the Electron ?)
**Uncaught TypeError: Cannot read properties of null (reading 'appendChild')**
```
    (function () {
      window.addEventListener("DOMContentLoaded", () => {
        const e = document.createElement("script");
        e.src = "chrome-extension://fnfbhokidopghpkcappjidaeidnonahi/ruffle/ruffle.js";
        document.head.appendChild(e);
      });
    })();
```

**Comment by ikreymer** [comment]
Should be fixed in 0.9.5
