### ISSUE TITLE
WARC/1.0 download: mixed use of hashes (sha1 vs. sha256); wrong format (format: WARC File Format 1.1)

### ISSUE THREAD

**Issue by steph-nb** [webrecorder/archiveweb.page#132]
Hi,

when recording a webpage with
software: Webrecorder ArchiveWeb.page 0.9.4, using warcio.js 2.0.1
and downloading the crawl as a WARC/1.0 warc.gz, there are two bugs:

1. The indicated format is wrong: format: WARC File Format 1.1 instead of format: WARC File Format 1.0 (seems to have been like that for a long time already)
2. hashes are used in a mixed way (sha1 for responses and requests; sha256 for revisits):

WARC/1.0
WARC-Record-ID: <urn:uuid:b719c312-257b-5970-9527-b0917d199519>
WARC-Page-ID: 4v2sjff2bfbk93aqy2lqu
WARC-Target-URI: https://api.republik.ch/graphql
WARC-Date: 2023-01-12T12:44:18Z
WARC-Type: response
Content-Type: application/http; msgtype=response
WARC-Payload-Digest: sha1:R2BIEVL7XVFHDZYTGQFOR36KJJBRSLV7
WARC-Block-Digest: sha1:KGFRDC2PVPOYELEEBCCZQKJNFWNC2V35
Content-Length: 3345

WARC/1.0
WARC-Record-ID: <urn:uuid:d8ae6edf-0f23-594d-8401-98cd5ab7b67d>
WARC-Page-ID: 7k3fuaqnu3yx8ql57th4db
WARC-Payload-Digest: sha-256:7ea12cc835d5c3cf2475d120d4d85b499265cd6ce062700431ee98670d1df8db
WARC-Target-URI: https://cdn.repub.ch/frontend/_next/static/86a41cc873/_buildManifest.js
WARC-Date: 2023-01-12T12:44:45Z
WARC-Type: revisit
WARC-Profile: http://netpreserve.org/warc/1.0/revisit/identical-payload-digest
WARC-Refers-To-Target-URI: https://cdn.repub.ch/frontend/_next/static/86a41cc873/_buildManifest.js
WARC-Refers-To-Date: 2023-01-12T12:44:17Z
Content-Type: application/http; msgtype=response
Content-Length: 622

This should not be.
It should always be sha1 (as it used to be before).
I cannot verify how long it is mixed now, but in an old testcase with software: Webrecorder ArchiveWeb.page 0.7.7, using warcio.js 1.5.0 I found it to have been sha1 only.

Thanks and BR

**Comment by ikreymer** [comment]
The file format fix is easy as that's just in the info, but the sha-256 is a bit more tricky, since internally archiveweb.page uses sha-256 for digests. Maybe it should always stick with sha-256 in this case, I don't think anything in WARC/1.0 prevents using sha1. Ideally, WARC validation tools can support sha-256 and WARC/1.1.
Do you need WARC/1.0 specifically, or sha-1 support, or both?

**Comment by steph-nb** [comment]
Hi,

you are right, WARC/1.0 does not prevent from using sha256.
So, no need to change it, I agree.

At the moment I really need WARC/1.0 (but only small changes in our system would be needed to also allow WARC/1.1).
(Anyway, after all I found that the issues I faced were not related to this).

So there only stays the info fix, which is rather nice to have...

Thanks a lot and BR

**Comment by tw4l** [comment]
Info fix for WARC 1.0 in https://github.com/webrecorder/awp-sw/pull/3
