### ISSUE TITLE
Google Docs Issue

### ISSUE THREAD

**Issue by edsu** [webrecorder/archiveweb.page#138]
It appears that ArchiveWebPage is unable to record and play back a public Google Docs page. I tried when being logged in and not logged in with the same result.

I tested with https://docs.google.com/document/d/1R_aVUrbAmkVXFF1vJWxnXE03FBtpxE8jkHF9P53n4Qk/edit 

Data appears to be collected, but there always seems to remain 1 URL pending.

<img width="1571" alt="Screenshot 2023-02-01 at 2 25 41 PM" src="https://user-images.githubusercontent.com/33829/216143063-c3f2fb5f-4cc0-425f-a31d-dea9d8be3420.png">

After waiting ~5 minutes, stopping and then viewing the archive an error pops up: 

<img width="1571" alt="Screenshot 2023-02-01 at 2 27 17 PM" src="https://user-images.githubusercontent.com/33829/216143249-354fd78d-0954-4902-bd54-4ae0db5ab9ab.png">

When clicking on OK a blank page with some header displays:

<img width="1571" alt="Screenshot 2023-02-01 at 2 27 27 PM" src="https://user-images.githubusercontent.com/33829/216143359-66889d95-e004-48dc-8710-8efdd53c98ab.png">

**Comment by ikreymer** [comment]
Just remembered the google docs switched to canvas based rendering:
https://workspaceupdates.googleblog.com/2021/05/Google-Docs-Canvas-Based-Rendering-Update.html
We are not saving the image from a <canvas> so that makes it much more difficult to archive and replay.

**Comment by ikreymer** [comment]
Turns out was fixable via additional wombat override, fixed in 0.9.7
