### ISSUE TITLE
Facebook-pages- can´t acces extension

### ISSUE THREAD

**Issue by Klindten** [webrecorder/archiveweb.page#139]
![image](https://user-images.githubusercontent.com/74599011/216307065-98ac491b-e440-4dbf-ac16-14c01f5a62a0.png)

On Chrome...

Sorry, there was an error starting recording on this page. Please try again or try a different page.

Error Details: Cannot access a chrome-extension:// URL of different extension

Also have issues on other sites  - but only in some instances: 

Sorry, there was an error starting recording on this page. Please try again or try a different page.

Error Details: Debugger is not attached to the tab with id: 931327157.

**Comment by ikreymer** [comment]
Do you have other extensions installed? Based on the error, it could be that another extension is interfering with the recording. If so, try disabling other extensions, or creating a profile that only has ArchiveWeb.page
Opening the page you want to archive in a new tab may also help.

**Comment by Klindten** [comment]
Thanks.  I had around 40 extensions installed and in use. Disabling them all _and_ loading a new tab I could get it to work again. Most likely it would be Tab Expender that caused it: https://chrome.google.com/webstore/detail/tab-suspender/fiabciakcmgepblmdkmemdbbkilneeeh. 

I think a Chrome profile with only archiveweb.page as you suggested would make the most sense since some other extensions are used a lot.
