### ISSUE TITLE
Can add in a html file uploader to the archiveweb.page please.

### ISSUE THREAD

**Issue by KaineRecycler** [webrecorder/archiveweb.page#144]
Instead of using urls for archiveweb.page app can you add in a html file uploader to archiveweb.page app please which users can easily browse and archive the web by uploading a html file to the archiveweb.page extension for chrome Firefox or brave browser please.

**Comment by KaineRecycler** [comment]
And can you also do the same thing but for the archiveweb.page stand alone app that is still in development.
A html file uploader for uploading offline webpages from either downloaded from the web or downloaded from the web archive so that it can easily be transferred from your mobile device to your computer and from there it can be easily interactive with archiveweb.page but only for the stand alone app that is still in development.

**Comment by tw4l** [comment]
Hi @KaineRecycler - the primary purpose of archiveweb.page and Webrecorder tools is to archive the live browser experience of a website, so I'm not sure that we'd want to support uploading just HTML files - there may be quite a bit missing in terms of a website's functionality that way.

I will keep this issue open to see if other folks have use cases for this type of behavior, but it's not really the direction that this project is going at least for the moment.

That said, if you're able to capture websites as WACZ or WARC files via this extension or our crawler, that should meet your use case of being able to replay the pages later on, including offline. Is there a use case that isn't covered by that workflow? Sites that are no longer online and can't be captured that way, maybe?

**Comment by KaineRecycler** [comment]
But anyway earlier when I tried to view my warc file it shows me a blank webpage so how do i view my full warc files through archiveweb.page add on extension and then interact with them easily without installing any warc file tools on my chromebook computer.

Besides I have already downloaded websites from my ipad and transfer them to Google drive on my chromebook computer
