### ISSUE TITLE
Archives sometimes becoming broken after saving more pages

### ISSUE THREAD

**Issue by ZheniaZuser** [webrecorder/archiveweb.page#149]
For example:
I was saving many pages from this site, and while doing it I checked the saved copy a few times - it worked properly. But after I finished, I found the saved became broken. But after a few minutes it started to work again (without doing anything between). 
Now, when I try to export, then open with Replayweb.page or import in other Chrome copy (in VM) it is broken in the same way again.

When I try to reproduce this by archiving it into new archive - it works even after export (but I saved only few pages in this case).
I had same problem before with other sites after saved a lot of pages.

working (before export): https://youtu.be/b4wyxljN8_M
corrupted: https://youtu.be/81ckDjJDgV8

Here is copy of Chrome's app data where it is archived first (1 GB) ([from Chrome Portable](https://portableapps.com/apps/internet/google_chrome_portable): https://drive.google.com/file/d/1w3hQ_jWe4sA43FBZmihxZuNTv6ye1RYR/view?usp=sharing

**Comment by ZheniaZuser** [comment]
Broken corrupted (620 mb): https://drive.google.com/file/d/1w9OhmfvBUagCUUJyJ0YHwR1PADoYFMqY/view?usp=sharing

**Comment by tw4l** [comment]
Hi @ZheniaZuser, thank you for the bug report!

> Broken corrupted (620 mb): https://drive.google.com/file/d/1w9OhmfvBUagCUUJyJ0YHwR1PADoYFMqY/view?usp=sharing

I don't seem to be able to reproduce the issue - the WACZ linked here loads fine in replayweb.page for me, and using the extension to archive designmorphine.com works fine, even after adding new data a few times.

Is it possible that something in your browser (maybe another extension?) is causing the issue? Can you try to reproduce using a clean version of Chrome/Chromium or in a private window?

**Comment by ZheniaZuser** [comment]
Hi,
> Can you try to reproduce using a clean version of Chrome/Chromium or in a private window?

Works fine now. I guess I had outdated version of extension installed. Updated Replayweb.page - now works here too.
