### ISSUE TITLE
Facebook recording using the extension fails with ServerJS based data-sjs payload content length mismatch

### ISSUE THREAD

**Issue by tsemachh** [webrecorder/archiveweb.page#152]
Example url:
[https://www.facebook.com/barackobama/posts/pfbid02DtgpT3LhF1fXaMd1Xk6w561TAMp8EucYsoZkqtNKcioGmY8VrWtdaEbTxVHTPeucl](https://www.facebook.com/barackobama/posts/pfbid02DtgpT3LhF1fXaMd1Xk6w561TAMp8EucYsoZkqtNKcioGmY8VrWtdaEbTxVHTPeucl)
When trying to record error is thrown from FB code:
```
b = a.dataset.contentLen;
if (a.textContent.length.toString() !== b) {
    if (i >= 1) {
        i -= 1;
        l(a);
        return
    }
    c("FBLogger")("serverjs_listener").addMetadata("COMET_INFRA", "SIZE", a.textContent.length.toString()).mustfix("ServerJS based data-sjs payload content length mismatch")
}
```
Debugging it looks like it's 1 character mismatch , this happens in Ubama's posts I don't know what's the root cause for this.
I tried many other FB posts , doesn't seem to have same issue there.
Thanks
Tsemach

**Comment by rikifrank** [comment]
Hi, I got the same error too
@tsemachh have you find anything?

**Comment by ikreymer** [comment]
I think this error can probably be ignored - I've seen this but there's no noticeable effect on functionality, and probably caused by the rewriting. It's probably fixable, but may not be worth the effort at this point.
