### ISSUE TITLE
IPFS not starting 

### ISSUE THREAD

**Issue by s925439** [webrecorder/archiveweb.page#155]
i have tried to start IPFS sharing on 2 different computers, using both the extention and the electron application. in addition to running the application in a sandboxed and unsandboxed enviorment, the problem is that it infinitely gets stuck and doesnt go anywhere, ive tried both the extention and the desktop app so far, any ideas or ways to find out the root cause would be appreciated.

**Comment by RangerMauve** [comment]
Are you able to run an IPFS (kubo) daemon outside of the app?

One thing to watch out for as well is if oyu have something listening on port `8080` on your computer since that can conflict with the default configuration of Kubo

**Comment by s925439** [comment]
> Are you able to run an IPFS (kubo) daemon outside of the app?
> 
> One thing to watch out for as well is if oyu have something listening on port `8080` on your computer since that can conflict with the default configuration of Kubo

i am able to run kubo outside of the app.

also ive tested this on a clean install in the past which doesnt have anything installed on 8080 outside of kubo itself, which doesnt change anything sadly.

**Comment by ikreymer** [comment]
With 0.10.1, you should now also see an error if IPFS can't be reached. Tested this with above settings and local kubo node and should be working. Closing for now.
