### ISSUE TITLE
Refresh loop due to window.location

### ISSUE THREAD

**Issue by tcyrus** [webrecorder/archiveweb.page#156]
I had some issues with replaying archives of Vite sites ([example](https://neural.love/ai-art-generator/1ede9fe2-9a61-6fe8-b093-25bfc69c7b3b/biopunk-factory))

I believe this is because of improper handling of relative paths for [`import()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import).

Here's my best explanation

```js
// Source: https://neural.love/assets/index.a9ce0e1b.js
var something = import('./index.e5ec4c6b.js');

// Live Page: Imports https://neural.love/assets/index.e5ec4c6b.js
// Replay Page: Imports https://neural.love/1ede9fe2-9a61-6fe8-b093-25bfc69c7b3b/biopunk-factory/index.e5ec4c6b.js
```

I'm guessing this is an issue specific to replaying archives using ArchiveWeb.page, as recording seems to be fine. I tested this on the Chrome extension as well as the Desktop App.
This probably affects a decent chunk of Single Page Applications.

**Comment by ikreymer** [comment]
I believe the replay should now work on https://replayweb.page / app 1.8.0+
Let us know if it doesn't - new release of archiveweb.page also coming soon.

**Comment by tcyrus** [comment]
Thanks for the fix. My replay works now and I'm not seeing the import errors in the console.
The other SPA I was trying to back up isn't working, but I don't see any errors in the console. I'll try debugging that more on my own and I'll make a separate issue for that.
Just out of curiosity; is there a reason that you're using inequality (`!=`) rather than strict inequality (`!==`)? I'm not extremely familiar with the `Location` object, so this could be related to some web browser behavior that I don't know about.

**Comment by ikreymer** [comment]
> Just out of curiosity; is there a reason that you're using inequality (`!=`) rather than strict inequality (`!==`)? I'm not extremely familiar with the `Location` object, so this could be related to some web browser behavior that I don't know about.

Yea, this was mostly to err on side of less redirects, since the property assignment will coerce it to a string, if object being assigned is not a string, but evaluates to the same URL, then we don't want to assign it still, even if it's not strictly equal.
