### ISSUE TITLE
STATUS_ACCESS_VIOLATION on Chrome Extension

### ISSUE THREAD

**Issue by tcyrus** [webrecorder/archiveweb.page#160]
I somehow managed to trigger `Error code: STATUS_ACCESS_VIOLATION` when trying to record a Tumblr page using the latest version of the Chrome extension.

The only actions that I took that might have caused this is that I manually reset my cookies using the dev console before loading the page.

The page loads fine when not recording and the replay technically works (site name and favicon are broken).

This issue doesn't occur on the Electron version, but I'm unable to import the archive from the Electron version because of #158 

I tried loading the extension dev console and couldn't find anything that would help me debug this. It appears that the page is somehow managing to load in the background, which means the capture is still running even though I can't see the page.

**Comment by ukaserge** [comment]
Did you managed to solve this problem? few months ago it was fine. but lately status_access_violation happen when i run extension. when its not run. Everything is normal.

**Comment by ZheniaZuser** [comment]
This happens often on Brave.
For example: start recording this: https://syntystore.com/ , click on "Polygon series link"
![image](https://github.com/webrecorder/archiveweb.page/assets/125911407/90e81a1d-2bcb-4d93-bc33-cfdcc76afde4)

**Comment by ikreymer** [comment]
@ZheniaZuser thanks for adding a consistent repro! I think the STATUS_ACCESS_VIOLATION might be particular to Windows, on mac, the page also crashes but with a different message 'error code 11' message.

I thought it was due to other extensions being in the way, but might now be happening on its own.

My guess is that its a new bug in Chromium, but will try to investigate further :/

**Comment by ZheniaZuser** [comment]
> This happens often on Brave. For example: start recording this: https://syntystore.com/ , click on "Polygon series link" ![image](https://user-images.githubusercontent.com/125911407/258663292-594fea48-d365-4b8e-ba15-225ec74c6c91.png)

Now this happens in Chrome too

**Comment by ikreymer** [comment]
Think I have a fix for it upcoming release, I think some change in recent version of Chromium has caused it to happen

**Comment by ikreymer** [comment]
This is now fixed in the 0.11.1 release, both Chrome and Brave.
