### ISSUE TITLE
Add initial Browsertrix Cloud integration.

### ISSUE THREAD

**Issue by ikreymer** [webrecorder/archiveweb.page#164]
On the new settings page, add option to enter Browsertrix Cloud credentials (URL endpoint, username, password).
Also add a popup to support uploading an archive/collection to Browsertrix Cloud, possibly as a popup, or inline similar to IPFS share..
Depends on webrecorder/browsertrix-cloud#929 API support

**Comment by Shrinks99** [comment]
It's in!  Released in 0.11.0!
