### ISSUE TITLE
my-web-archive.wacz  Size:8 GB loads extremely slow and will take forever to index the page

### ISSUE THREAD

**Issue by nataleeonajourney** [webrecorder/archiveweb.page#166]
please help dear team :

my-web-archive.wacz  Size:8 GB loads extremely slow and will take forever to index the page

is there a way to make it faster so that pages inside the recorded archieve " my-web-archive.wacz " can load faster so that it becomes usable.

Thank you

**Comment by ZheniaZuser** [comment]
I have 669 mb wacz wich also loads extremely slowly when importing it into extension in Brave. The file was just created and exported from there

**Comment by ikreymer** [comment]
If you just want to replay the WACZ, you should use https://replayweb.page/ and it should load relatively fast.

If you'd like to import it into ArchiveWeb.page to add to the archived item, and you're using Brave, it's a known issue and there's a workaround to make it load faster, described in: #212
