### ISSUE TITLE
When Replay Record Page 404!

### ISSUE THREAD

**Issue by java30kcoding** [webrecorder/archiveweb.page#172]
I record a page, and got some URL 404 when replay.
eg:
Replay warc files got 404 by URL:
http://localhost:5471/w/id-30fd344be982/:37a8eec1ce19687d132fe29051dca629d164e2c4958ba141d5f4133a33f0688f/20230720065542mp_/http://xxx.xxx/tarsier-xxx/xxx/configuration/getConfiguration

But when I saw URLs in wacz file and click same url, request location is different.Like this:
http://localhost:5471/w/id-30fd344be982/:37a8eec1ce19687d132fe29051dca629d164e2c4958ba141d5f4133a33f0688f/20230720065544mp_/http://xxx.xxx/tarsier-xxx/xxx/configuration/getConfiguration

Them is not same：20230720065542mp_&20230720065544mp_
So why does them url not same, and how can I resolve it, Thx~

![image](https://github.com/webrecorder/archiveweb.page/assets/32125339/d0ffbb00-c3b3-4a2d-8880-eaa1e8954fc3)
![image](https://github.com/webrecorder/archiveweb.page/assets/32125339/f9d2c5e4-f86e-4bf1-9e6e-10db1d7c47bb)

**Comment by java30kcoding** [comment]
File like js、css、html use 20230720065542mp_ are success.
![image](https://github.com/webrecorder/archiveweb.page/assets/32125339/7330ed7f-7a34-449a-b285-30c3c75d55b8)

**Comment by ikreymer** [comment]
Seems possibly a POST vs GET issue. Very likely fixed by now, try again in the latest, otherwise hard to say more without looking at the WACZ file.
