### ISSUE TITLE
Archiving of page containing vimeo video results in browser crash

### ISSUE THREAD

**Issue by steph-nb** [webrecorder/archiveweb.page#186]
Hi,

when trying to record this page:
https://www.republik.ch/2019/11/27/heute-abend-live-wir-reden-mit-mely-kiyak-ueber-neue-schweizer-literatur

After about 1-2 minutes the browser crashes entirely.

This happens both on windows10 and ubuntu, using chrome116, and archiveweb.page V0.11.2.

**Comment by ikreymer** [comment]
I wasn't able to repro the crash anymore, but the video is 2.1GB, and so it will likely fail unless it has the memory to stream it into the browser directly. For something like this, Browsertrix Crawler may be better, as it can stream directly to disk, as its a bit more optimized for larger files.
