### ISSUE TITLE
webrecorder fails to archive VK video

### ISSUE THREAD

**Issue by dteyssou** [webrecorder/archiveweb.page#188]
archiveweb.page (in webrecorder browser extension) fails to capture a VK video page (https://vk.com/video-57424472_456295738). The resulting archive crashes the Chrome browser (Version 116.0.5845.179 (Build official) (arm64)) in the extension replay and shows only the header (without any video) in replayweb.page.

**Comment by tsemachh** [comment]
The crash is related to:
[https://github.com/webrecorder/archiveweb.page/issues/194](https://github.com/webrecorder/archiveweb.page/issues/194)
I found it's chrome version issue , still there are many errors on the replay page when you download the wacz and put it on the replay web page

**Comment by ikreymer** [comment]
The crash is fixed in 0.12.4, and I was able to capture and replay the video with that version, so closing as fixed!
