### ISSUE TITLE
cannot download amboss website

### ISSUE THREAD

**Issue by 925670849** [webrecorder/archiveweb.page#190]
Sorry, there was an error starting recording on this page. Please try again or try a different page.

Error Details: Cannot access a chrome-extension:// URL of different extension

If the error persists, check the [Common Errors and Issues](https://archiveweb.page/guide/troubleshooting/errors) page in the guide for known issues and possible solutions.

**Comment by edsu** [comment]
What was the page you were trying to archive?

**Comment by ikreymer** [comment]
This is due to other extensions interfering with archiving. We'll see if there's a better fix, but for now, disabling other extensions should avoid this issue.
We've added this message to the common issues page as well.
