### ISSUE TITLE
POST request not handled correctly

### ISSUE THREAD

**Issue by bricas** [webrecorder/archiveweb.page#191]
Form in question: https://archives.gnb.ca/ResearchTools/NewspaperDirectory/default.aspx?culture=en-CA
(the "View Newspaper" drop-down).

Related forum post: https://forum.webrecorder.net/t/capturing-a-post-form-used-for-navigation/428

As noted, when I tested a couple of POST captures, the form only ends up on the last one I tried.

@edsu noted that the form data is very large (~50K) which may be part of the issue.

**Comment by ikreymer** [comment]
Somehow missed the issue, fixed in #192 - now adding truncation of very large POST query arguments to 512, which should help in this case, as it allows other query arguments to be included.

Will be part of 0.11.3 release.

**Comment by edsu** [comment]
So it sounds like this change *adds* truncation and it wasn't being truncated before? Maybe I wasn't being clear, but I thought truncation might have been *causing* the wrong POST response from being returned. Could *not* truncating have caused the problem that we were seeing?
