### ISSUE TITLE
Failing to record (or replay) http://datagenetics.com/blog/july12019/index.html

### ISSUE THREAD

**Issue by Binarus** [webrecorder/archiveweb.page#195]
At first, thank you very much for archiveweb.page and replayweb.page! They are the only tools that allow accurate archiving and viewing of nearly all web pages I have encountered so far.

However, I'd like to report that I couldn't record (archive) the following page: http://datagenetics.com/blog/july12019/index.html

Actually, I don't know whether it is not recorded correctly or whether there is a problem when replaying it. Since I am not that deep in web technologies, maybe I am doing something wrong.

I am using the Webrecorder ArchiveWeb.page 0.11.3 extension in Chrome on Windows 10 Enterprise x64 and have tried recording with and without autopilot. I have activated and inactivated the animations on the page and have clicked around everywhere while recording. However, when replaying the page, some of the graphics and buttons are missing.

It would be very nice if this could be fixed. I am willing to assist as far as I am able to.

Best regards,

Binarus

**Comment by ikreymer** [comment]
The replay for this is fixed in replayweb.page 2.0.2, and will be in next update of archiveweb.page

**Comment by ikreymer** [comment]
This should now work!

**Comment by Binarus** [comment]
Better late than never: Although it's way too late, I would like to thank you for having fixed the issue. I highly appreciate your effort and your time.
