### ISSUE TITLE
The Ruffle emulator does not yet support ActionScript 3

### ISSUE THREAD

**Issue by ZhangSanMo** [webrecorder/archiveweb.page#197]
When I wanted to record a website which is a **Virtual reality and 360° panorama technology** , it shows me a message: The Ruffle emulator does not yet support ActionScript 3, required by this content.If you choose to run it anyway, interactivity will be missing or limited.
![image](https://github.com/webrecorder/archiveweb.page/assets/20506880/60371486-0de6-4e44-8cf5-f2ee282990e8)

**Comment by Shrinks99** [comment]
Looks like the site you are trying to archive is still using Adobe Flash, specifically using features of Flash that Ruffle — the Flash emulator we use — doesn't support yet.

You can check out Ruffle's ActionScript 3 support page [here](https://ruffle.rs/compatibility/avm2).
