### ISSUE TITLE
Add issue categories \ link to replayweb.page issues?

### ISSUE THREAD

**Issue by ZheniaZuser** [webrecorder/archiveweb.page#202]
For example, archiveweb.page can also replay sites, so if there is problem with it, most people would probably go here (archiveweb.page) to report it. And browser extension does not even have separate replay-only version.

**Comment by Shrinks99** [comment]
Yeah, I've done this for Browsertrix and ReplayWebpage, this is the last major repo for me to tackle with issue types.  Thanks for the reminder :)
