### ISSUE TITLE
Issue rendering filterable content

### ISSUE THREAD

**Issue by jakebickford** [webrecorder/archiveweb.page#21]
Hello!

Thanks for your great work on this project. We have recently switched from using Webrecorder desktop and I'm enjoying exploring archiveweb.page. 

I hope this question isn't too specific, but hopefully it will be useful to others dealing with similar content. 

I'm trying to capture the (I assume database driven) content at the bottom of these pages:

https://www.therenditionproject.org.uk/prisoners/index.html
https://www.therenditionproject.org.uk/documents/index.html
https://www.therenditionproject.org.uk/flights/renditions/index.html

They seem like they're capturing ok but when you play them back it loads the main page but not the filterable content at the bottom. Strangely the more complicated page here (https://www.therenditionproject.org.uk/flights/flight-database.html) does seem to work ok.

I have also tried using Conifer with the remote browsers that support flash and java but seem to have the same problem.

I've found a few instances on the internet archive where the content does render, though it seems to vary from crawl to crawl: https://web.archive.org/web/20210117163104/https:/www.therenditionproject.org.uk/prisoners/index.html 

Anyway, I thought I'd flag it in case it's of interest.

All the best,

Jake

**Comment by ikreymer** [comment]
Thanks for reporting, the issue/fix is in wabac.js (related to JSONP rewriting that wasn't broad enough) -- should be fixed in a future update!

**Comment by jakebickford** [comment]
Brilliant, thanks Ilya!

**Comment by ikreymer** [comment]
Now fixed in 0.5.12 release.
