### ISSUE TITLE
[Bug]: Stuck at "Loading Archives"

### ISSUE THREAD

**Issue by MehtabHasnain** [webrecorder/archiveweb.page#217]
### ArchiveWeb.page Version

ArchiveWeb.page App + Extension 0.11.4

### What did you expect to happen? What happened instead?

Extension is stuck at "Loading Archives" in Home Page. Also after recording a page, clicks of "View Archived Page" from the popup window of the extension returns Black page. 
This behavior was noticed in Brave browser in Mac (intel). While tested in Arc Browser, the extension is working as expected.
I tried both Github version and Chrome web store version, the problem persists.

So, I downloaded the .dmg for the app from Github and the same problem also persists there too.

### Step-by-step reproduction instructions

Bug experienced with both Extension (Brave) and desktop app (Mac intel).

1. Home Page:

![1](https://github.com/webrecorder/archiveweb.page/assets/50154152/eda7b69f-2cf8-4dc6-bdac-77cdee74de26)

2. Extension popup:

![2](https://github.com/webrecorder/archiveweb.page/assets/50154152/7b2ed55c-1c55-4ae9-b201-754604c70bbe)

3. Returns Blank Page when clicked on "View Achieved Page":

![3](https://github.com/webrecorder/archiveweb.page/assets/50154152/ce0d3969-aaed-49eb-ba49-6a513454128a)

**Comment by ikreymer** [comment]
Can you open the dev console and see if there are any error messages there?
I think this should be fixed in 0.12.0, I suspect its a dependency issue like 'CarIteratorBase is undefined' which should be fixed in 0.12.0, but not 100% sure, since I wasn't able to repro this issue thus far.

You are seeing this in the downloaded app as well?

**Comment by MehtabHasnain** [comment]
Fixed in 0.12.0!

Thank you!

**Comment by pboiski** [comment]
I'm having the same issue with the standalone app on Linux, with both 0.12.0 and 0.12.1.
It works on 0.11.3.

These are the errors I'm getting in the developer logs:
![Screenshot_20240611_142553](https://github.com/webrecorder/archiveweb.page/assets/36693800/8d11cb66-c604-4425-b23a-f66916766ac1)

**Comment by Bewo** [comment]
Same here........
Tested in v.0.11.4, v.0.12.0, v.0.12.1 und v.0.12.2.... same issue.

v.0.11.3 works like a charm....
by the way: an option to disable the auto-update would be great...
![Bildschirmfoto 2024-07-04 um 13 05 07](https://github.com/webrecorder/archiveweb.page/assets/8536696/253fee0e-f8f8-4885-9c73-9460ef10dedf)

**Comment by ikreymer** [comment]
@Bewo this was a slightly different issue between the extension and the app, required a different fixed. Will be fixed in 0.12.4 App

**Comment by Bewo** [comment]
Perfect! v.0.12.4 works like a charme!!

@ikreymer Thanks for the quick fix!! And many thanks for all your work on this great tool!! :-)
