### ISSUE TITLE
extract files from the warc archive

### ISSUE THREAD

**Issue by seekingdeep** [webrecorder/archiveweb.page#22]
Hi there,
i was wondering, how can i extract the files (images,....etc) from the warc archive?

**Comment by edsu** [comment]
Maybe this is too specific but you could use the Python [warcio](https://github.com/webrecorder/warcio) library to write a program to iterate through the warc records, look for responses that have 'image' in the content-type, and then use the URL to create a path to write the content of the response to to the file system. Here's a little example of doing that:

https://gist.github.com/edsu/c2c85f633562e69f6db2a2d2d2c2517e

**Comment by seekingdeep** [comment]
You are amazing !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
