### ISSUE TITLE
[Replay Bug]:   Chrome keeps crashing  with view recorded page for a particular forum - ArchiveWeb.page extension

### ISSUE THREAD

**Issue by hamoudak** [webrecorder/archiveweb.page#224]
### ReplayWeb.page Version

v 0.11.3

### What did you expect to happen? What happened instead?

I was trying to archive selected pages of a forum .I tried to open a link of the archived pages ; chrome craches. any link of them the same issue happening . also, with view recorded page. so I downloaded the (WACZ) pages to play them with the desktop app , all is ok ? now the wacz file won't work if I import it to archive web.page to play pages, what to do to fix that? you can test this urls to see: 
https://majles.alukah.net/
https://majles.alukah.net/showthread.php?t=184791

_ it replays also well here https://replayweb.page/

### Additional details

note: arabic language
Chrome is up to date
Version 125.0.6422.61 (Official Build) (32-bit)

I have disabled all my extensions to record well.

windows ver: 10
1903 (OS Build 18362.1256)

sorry, it has to be opened in archiveweb.page issues, but I was in a hurry.

**Comment by ikreymer** [comment]
Undiagnosed crash on replay, duplicated of #194

**Comment by hamoudak** [comment]
It was me on webrecorder forum. do you mean there's no fix for this ?

**Comment by tw4l** [comment]
Hi @hamoudak , there's no fix yet but we will track progress in #194 since there was already an existing issue for this bug. Thanks!

**Comment by ikreymer** [comment]
This should now be fixed in the 0.12.4 release!
