### ISSUE TITLE
[Bug]: The app cannot load WARC and WACZ files after opening, and the files recorded on the app cannot be saved.

### ISSUE THREAD

**Issue by Yz-Crazy** [webrecorder/archiveweb.page#231]
### ArchiveWeb.page Version

v0.12.1，v0.12.2

### What did you expect to happen? What happened instead?

![CleanShot 2024-06-24 at 17 50 08](https://github.com/webrecorder/archiveweb.page/assets/42207246/287b0cca-c129-4637-92af-9582ca6f9b76)
![CleanShot 2024-06-24 at 18 01 42](https://github.com/webrecorder/archiveweb.page/assets/42207246/681893c4-1801-42cf-a25e-bc999bee42b9)
There is a long loading time, but the content does not load. Additionally, files recorded using the app cannot be saved. The recording is done using the latest version of the browser extension.

### Step-by-step reproduction instructions

macos 14.0
Intel Core CPU

window 10

ArchiveWeb.page version v0.12.1 ,v0.12.2

**Comment by Bewo** [comment]
Maybe the same issue as
https://github.com/webrecorder/archiveweb.page/issues/217

**Comment by ikreymer** [comment]
Fixed in 0.12.4 release!
