### ISSUE TITLE
[Bug]: ArchiveWebPage Desktop version cannot login til Browsertrix -  but it works in the Chromebrowser plugin

### ISSUE THREAD

**Issue by tuehlarsen** [webrecorder/archiveweb.page#232]
### ArchiveWeb.page Version

App v0.12.2

### What did you expect to happen? What happened instead?

login to browsertrix fails allways in the desktop version but not in the browserextension

![image](https://github.com/webrecorder/archiveweb.page/assets/12230847/360406fe-c4be-40f8-a0b1-c3ce94645693)

### Step-by-step reproduction instructions

se above

**Comment by ikreymer** [comment]
Fixed in 0.12.4 release!
