### ISSUE TITLE
[Bug]: ArchiveWebpage Desktop hangs in New Archiving Session

### ISSUE THREAD

**Issue by tuehlarsen** [webrecorder/archiveweb.page#233]
### ArchiveWeb.page Version

App v0.12.2

### What did you expect to happen? What happened instead?

 ArchiveWebpage Desktop hangs in New Archiving Session:
![image](https://github.com/webrecorder/archiveweb.page/assets/12230847/51900ad0-88dc-4ea8-bfef-dfbb1da3a49e)

### Step-by-step reproduction instructions

se screen dump above

**Comment by Bewo** [comment]
Maybe the same issue as
https://github.com/webrecorder/archiveweb.page/issues/217#issuecomment-2208707016

**Comment by ikreymer** [comment]
Fixed in 0.12.4 release!
