### ISSUE TITLE
Browser crashes when replaying archived Facebook page

### ISSUE THREAD

**Issue by kumushini** [webrecorder/archiveweb.page#236]
### ArchiveWeb.page Version

Extension v0.12.2

### What did you expect to happen? What happened instead?

I archived a Facebook page using Archiveweb.page Chrome extension. The browser crashes when trying to replay the archived Facebook page.

chrome-extension://fpeoodllldobpkbkabpblcfaogecpndd/index.html?source=local%3A%2F%2Fao9vuxei7nrz8vnaf658z#view=pages&url=https%3A%2F%2Fwww.facebook.com%2Fnppsrilanka&ts=20240704034121

### Step-by-step reproduction instructions

1. Visit Facebook page https://www.facebook.com/nppsrilanka
2. Archive with Archiweb.page chrome extension
3. Click replay current page or View archived pages and click on the archived Facebook URL

**Comment by ikreymer** [comment]
Unfortunately, this is a known issue with some sites, see: #194. We don't have a solution as it seems to be a bug in Chromium - the browser shouldn't crash.

**Comment by ikreymer** [comment]
This crash should now be fixed in 0.12.4 release!
