### ISSUE TITLE
Archives missing after update from 0.5.11 to 0.6.0

### ISSUE THREAD

**Issue by trych** [webrecorder/archiveweb.page#24]
As described in the title, I just updated to the most recent release and now after opening the program it tells me, I have no archives ...

I am on macOS 10.13.6, and just installed the update by replacing the previous version with the new one in the Applications folder. Are my archives still stored somewhere?

**Comment by trych** [comment]
Ok, a few moments after I posted this, the Archives show up again in the app, without me changing everything. Maybe it just needs a few moments to load them initially? Strange though as I just have three records in the app, so not an overwhelming amount. Anyways, the problem seems solved.

**Comment by ikreymer** [comment]
Hi, sorry about that, yes, it does seem that after the update to 0.6.0, because some internal paths changed, the archives do not appear right away. I'll see if there's a way to make this smoother, I believe this only happens on initial update to 0.6.0.
