### ISSUE TITLE
[Bug]: Crashing while recording Youtube Video on web.archive.org

### ISSUE THREAD

**Issue by yacylover** [webrecorder/archiveweb.page#241]
### ArchiveWeb.page Version

v0.12.4

### What did you expect to happen? What happened instead?

Hi,

I just tried to record [an archived Youtube video on web.archive.org](https://web.archive.org/web/20230506155257/https://www.youtube.com/watch?v=pGwAHF0iU60) but the Archiveweb.page App crashes :-(

Crashpad Client ID 9cce16e2-264d-4cd9-adcf-3e566d0ad9ca

Please fix

### Step-by-step reproduction instructions

1. Start the Archiveweb.page app

2. Navigate to any Youtube Video archived on web.archive.org

3. Start recording

**Comment by ikreymer** [comment]
ArchiveWeb.page really support re-archiving content from web.archive.org at this time. You can try https://express.archiveweb.page/ which had some experimental support for this. If you're dealing with a very large video, it may exceed the memory available in the browser, and that can cause a crash.
