### ISSUE TITLE
Ensure page loaded from POST request has correct page info (was: WACZ file replays in ArchiveWebPage but not ReplayWebPage)

### ISSUE THREAD

**Issue by edsu** [webrecorder/archiveweb.page#242]
### ReplayWeb.page Version

v2.1.1 (AWP 0.12.4)

### What did you expect to happen? What happened instead?

I created a small archive using ArchiveWebPage v0.12.4 of this page:

https://rescarta.lapl.org/ResCarta-Web/jsp/RcWebImageViewer.jsp?doc_id=040428be-8b21-4de1-9b1e-3421068c0f1c/cl000000/20190731/00000011

I exported the archive as a WACZ and then imported into ReplayWebPage and the page does not replay. It reports `Archived Page Not Found`. 

I then deleted the archive in ArchiveWebPage and imported the WACZ into ArchiveWebPage and the page replays ok.

### Step-by-step reproduction instructions

Using Chrome go to https://replayweb.page and load this WACZ file by URL:

https://edsu-webarchives.s3.amazonaws.com/tmp/lapl.wacz

If you try to replay the one page you will see the `Archived Page Not Found`.

<img width="1702" alt="Screenshot 2024-07-12 at 9 34 13 AM" src="https://github.com/user-attachments/assets/6eec51b6-ff5d-4383-b2de-cc3992c19ffb">

If you go to https://archiveweb.page and load the same URL you should see that it plays fine.

<img width="1702" alt="Screenshot 2024-07-12 at 9 34 16 AM" src="https://github.com/user-attachments/assets/cc859453-1761-488b-a85f-ed5d8fcb46e9">

### Additional details

I noticed in the dev console when using ReplayWebPage that there is a `RangeError: Invalid time value
` and that the page date in the interface is blank?

<img width="1702" alt="Screenshot 2024-07-12 at 9 36 40 AM" src="https://github.com/user-attachments/assets/f35099b4-c0e3-4af9-92c1-dc8076b02d32">

When using ArchiveWebPage there is no console error, but the page date shows up as "Invalid Date":

<img width="1702" alt="Screenshot 2024-07-12 at 9 36 35 AM" src="https://github.com/user-attachments/assets/32249fa3-651c-4d1c-b446-ebeb4fe26c70">

**Comment by ikreymer** [comment]
ArchiveWeb.page didn't handle POST request pages properly, since this is possible to arrive at a page from a POST request, it will now check for that, and update the page listing according. The attached WACZ wasn't created properly (hence the invalid date), but it is now fixed in 0.12.5. You should be able to archive a page after a POST request and then load it in ReplayWeb.page (though existing archives won't be affected).
