### ISSUE TITLE
Hi which is the latest Windows 7 working version?

### ISSUE THREAD

**Issue by tomasts248** [webrecorder/archiveweb.page#248]
### Context

Im getting error not valid win32 I assume electron is no supporting it..

### What change would you like to see?

Just point me the latest w7 working version...

Also may I ask how can I archive  awhole site without browsing the pages?

**Comment by ikreymer** [comment]
Sorry, there's no version of ArchiveWeb.page that will run on Windows 7, if you can get an old version of Chrome to run on it and install the extension, that may be your best bet, but I'd be surprised if it worked.

If you want to archive the whole site, we have our open source tools [Browsertrix Crawler](https://github.com/webrecorder/browsertrix-crawler) and [Browsertrix](https://browsertrix.com/) which we offer as a service as well.

**Comment by tomasts248** [comment]
I downloaded an older version and it actually worked, also i did install the latet version of the extension on a chromium based browser as well, but I realized it isnt possible to archive the whole page wich is what I was after..
