### ISSUE TITLE
[Replay Bug]: Facebook archive content display partial in replayweb page

### ISSUE THREAD

**Issue by rikifrank** [webrecorder/archiveweb.page#250]
### ReplayWeb.page Version

v1.8.15

### What did you expect to happen? What happened instead?

I archived facebook link (https://www.facebook.com/NBCNews) using Webrecorder ArchiveWeb.page extension
V0.11.3, I scroll done few pages to get as much content (about 100 posts) , please note I archived feed page and not a post
when I tried to replay the wacz in ArchiveWeb.page itself It crashed my chrome (Version 123.0.6312.87 (Official Build) (arm64))
I download the wacz to my computer and tried to replay it in ReplayWeb.page (v1.8.15), It only play the first posts there, up to 22 posts , I needed to wait each scrolling to continuance loading of the content 
my wacz is here : https://drive.google.com/file/d/1AQXl7z52n_GwVFvW7e0w_fC80sKnyuo7/view?usp=sharing

### Step-by-step reproduction instructions

1. navigate to https://www.facebook.com/NBCNews
2. start recording using Webrecorder ArchiveWeb.page extension
3. download the wacz
4. navigate to https://replayweb.page/
5. import file and choose the downloaded wacz
6. click to replay content

**Comment by ikreymer** [comment]
Unfortunately, this is mostly a capture issue, so moved this issue here.
The 0.12.6 release of ArchiveWeb.page should include a variety of fixes which should make capture and replay of Facebook pages work much much better, though you'll need to capture again. The fix also includes fixes to capturing videos, which should be getting capture in the timeline as well.

**Comment by ikreymer** [comment]
0.12.6 is out, so will close this for now. Can't say all FB issues are 100% fixed, but I believe the main issue should be addressed (for now), this is something that will require constant maintenance unfortunately.
