### ISSUE TITLE
[Bug]: web-recorder can not detect facebook video

### ISSUE THREAD

**Issue by aboudeh-webdev** [webrecorder/archiveweb.page#272]
### ArchiveWeb.page Version

v0.13.2

### What did you expect to happen? What happened instead?

web-recorder is unable to detect facebook videos since a week, it seems that facebook has made some changes to their data model.

### Step-by-step reproduction instructions

i was trying to archive facebook video post using the chrome extension

https://www.facebook.com/watch?v=1259613418712038

<img width="649" alt="Screenshot 2024-11-12 at 15 20 18" src="https://github.com/user-attachments/assets/6b53983c-b2f3-473a-872c-1c9650420a5d">

**Comment by ikreymer** [comment]
Yes, they've changed something again, making it harder to archive the videos, unfortunately. Was working perfectly just a couple of months ago..
