### ISSUE TITLE
[Bug]:archiveweb desktop app crashes when archiving facebook video or photo posts

### ISSUE THREAD

**Issue by aboudeh-webdev** [webrecorder/archiveweb.page#273]
### ArchiveWeb.page Version

App v0.13.3

### What did you expect to happen? What happened instead?

the app will crash when archiving video or photo facebook posts

https://www.facebook.com/watch?v=1259613418712038
https://www.facebook.com/photo/?fbid=554740210823137&set=a.413654228265070

### Step-by-step reproduction instructions

https://github.com/user-attachments/assets/3ff9e005-af9d-40f8-bd4c-a7b907f0733d

**Comment by ikreymer** [comment]
Should be fixed in 0.14.0 along with #272
