### ISSUE TITLE
WACZ download fails on Linux appimage version (was: Allow defining "pages" in archive)

### ISSUE THREAD

**Issue by deltabravozulu** [webrecorder/archiveweb.page#29]
If one creates a sizable file (e.g. a 60 GB WARC or WACZ), it can be incredibly challenging to find the "home" page of your archive. It would be useful to be able to configure this. 

As an example, upon loading a 60 GB WARC into a local electron version of replayweb.page AppImage, it says in the Page tab,
```
0 Pages Found
----
No "Pages" are defined in this archive. Browser by URL.
```

A similar experience occurs in the old Webrecorder-Player AppImage.

**Comment by ikreymer** [comment]
Are you using ArchiveWeb.page to create the archives? If so, the pages should be defined automatically as you browse.
Or, are you importing WARCs / WACZ files into replayweb.page, created somewhere else - in which case this is more a replayweb.page question...

**Comment by deltabravozulu** [comment]
@ikreymer  Yeah I am using the .AppImage version of ArchiveWeb.page. It actually is unable to export the archive to a usable WACZ (the file of the WACZ is equivalent to the, but it can spit out a WARC. IPFS also crashes when trying to share (the terminal logs show the IPFS servers spawning but after a few or so GET's of http://localhost:5471/replay/sw.js it crasehs. 

The .AppImage works fine with an 8MB and a 1GB crawl for both WACZ and WARC files and these also serve via IPFS. 


Which actually brings up a question I had mused over but hadn't dug into the code to figure out-- is there a command one can issue either in a terminal or the JS console in the dev tools on the .AppImage to build a WACZ or WARC from the files in the `~/.config/archivewebpage/IndexedDB/http_localhost_5471.indexddb.blob` directory (or one of its parent directories)?

**Comment by ikreymer** [comment]
> @ikreymer Yeah I am using the .AppImage version of ArchiveWeb.page. It actually is unable to export the archive to a usable WACZ, but it can spit out a WARC. Interestingly, the filesize of the WACZ at 21337548 kilobytes is nearly equivalent to the WARC at 21328212 kilobytes.
> 

Seems like this is the main issue/bug somewhere. Do you see any errors in the devtools? You should be able to open devtools in the app through the default shortcut, or the menu (though I haven't tested this on the AppImage version).

> IPFS also crashes when trying to share (the terminal logs show the IPFS servers spawning but after a few or so GET's of http://localhost:5471/replay/sw.js it crashes.
> 

Hm, the entire app crashes? The IPFS sharing is also using a WACZ.

> The .AppImage works fine with an 8MB and a 1GB crawl for both WACZ and WARC files and these also serve via IPFS.
> 

It could be the size.. it looks like its ~20GB archive that's being exported?

> Which actually brings up a question I had mused over but hadn't dug into the code to figure out-- is there a command one can issue either in a terminal or the JS console in the dev tools on the .AppImage to build a WACZ or WARC from the files in the `~/.config/archivewebpage/IndexedDB/http_localhost_5471.indexddb.blob` directory (or one of its parent directories)?

In theory, maybe, but there isn't a standard/guaranteed way to do this. Chromium is using LevelDB under the hood but there's a custom comparator.. Ideally, can just fix this issue. If the WARC download is working, hopefully something straightforward..

**Comment by ikreymer** [comment]
I think the issue is that JSZip library does not support ZIP64, which is necessary to export WACZ files >4GB.
Created a separate issue to track this (#36). For now, try to export pages in smaller chunks to avoid reaching 4GB for WACZ files.
