### ISSUE TITLE
Is exposing ArchiveWeb.page as a CLI / Node JS library feasible?

### ISSUE THREAD

**Issue by pirate** [webrecorder/archiveweb.page#31]
In the ArchiveBox community we often get users asking for higher-fidelity alternatives to ArchiveBox, and I always [direct them to ArchiveWeb.page](https://github.com/archivebox/archivebox#comparison-with-other-self-hosted-archiving-options) but oftentimes they come back saying they need something that works as a CLI command.

If ArchiveWeb.page could expose a oneshot `$ archivewebpage 'https://example.com' -o example.com.warc` CLI or nodejs interface (similar to how [SingleFile exposes a CLI](https://github.com/gildas-lormeau/SingleFile/blob/master/cli/README.MD)), I think a lot more people would be able to integrate it into their workflows and projects.

> SingleFile can be launched from the command line by running it into a (headless) browser. It runs through Node.js as a standalone script injected into the web page instead of being embedded into a WebExtension. To connect to the browser, it can use Puppeteer or Selenium WebDriver. `single-file --

I'd love to hear your thoughts on this / see if it's as easy as SingleFile's approach to provide a CLI interface. If it's too much work / not something you'd be keen on building yourself, even providing an outline of how you think it could be implemented would be helpful (to get an idea of how hard it is / what modifications would need to be made).

---

I also have some selfish reasoning for wanting this ;) Given how stunningly good ArchiveWeb.page is at saving difficult content compared to all the other options, I've been drawn more and more to the idea of integrating it as an [extractor plugin](https://github.com/ArchiveBox/ArchiveBox/blob/dev/archivebox/extractors) in ArchiveBox (similarly to how we did it with [SingleFile](https://github.com/ArchiveBox/ArchiveBox/blob/dev/archivebox/extractors/singlefile.py)).

The way ArchiveBox is architected allows us to use arbitrary 3rd party software as ["plugins"](https://github.com/ArchiveBox/ArchiveBox/blob/dev/archivebox/extractors/) to save pages, with varying levels of work required to integrate: Python libraries (easiest), JS/node (medium difficulty), and arbitrary binaries via shell commands (hardest). I've considered integrating `pywb` in the past, but I decided against it because I didn't want to cause any headaches / ill-will by trying to mix two already complicated pieces of software with significant feature and audience overlap.

Correct me if I'm wrong, but I think ArchiveWeb.page might be a better fit than `pywb` for plugin-style integration into ArchiveBox. It seems to excel at archiving individual pages or small groups of pages, and focuses less on curating huge collections of many archived pages (e.g. someone's entire browsing history over years). If it works well, I could see it becoming a significant part of the ArchiveBox's value proposition, and I'd be happy to market ArchiveWeb.page significantly in our [README](https://github.com/archivebox/archivebox#comparison-with-other-self-hosted-archiving-options) and [docs](https://github.com/ArchiveBox/ArchiveBox/wiki/Web-Archiving-Community#other-archivebox-alternatives), and share a portion of our donations with you to further support ArchiveWeb.page development.

Either way, I think providing a CLI interface would have many good use cases besides integration with ArchiveBox.

Related issues:

- https://github.com/webrecorder/archiveweb.page/issues/27

**Comment by Artoria2e5** [comment]
I feel it might be easier to work it through the Electron route than through the Puppeteer + Chromium route for now. I will start a fork to see what I can do with it.

**Comment by ikreymer** [comment]
https://github.com/webrecorder/browsertrix-crawler provides such as CLI / extensible crawler that captures web content in a very similar way to the extension.
