### ISSUE TITLE
Support client-zip to have zip64 support and valid downloads of 4GB> WACZ files

### ISSUE THREAD

**Issue by ikreymer** [webrecorder/archiveweb.page#36]
Currently WACZ output is limited to around ~4GB size WACZ files, due to lack of zip64 in jszip.
Will need to switch to zip.js to be able to create larger WACZ files.

**Comment by ikreymer** [comment]
@anisa-hawes this should finally be fixed in 0.7.11 and up, it should be able to download large WACZ files without issue!
The desktop app is now out, and the extension should be available as soon as it's approved!

**Comment by anisa-hawes** [comment]
Hello, @ikreymer. Thank you for this note! I've updated to 0.7.11 today and have been experimenting. 

The download progressed until (at my latest attempt) the WACZ file showed as >3.8GB.... but then disappeared from Downloads before completing...

App remained open throughout (no crashing).

**Comment by ikreymer** [comment]
Thanks for testing! Hm, the crash seems unrelated to the particular issue here, and is likely something else. The disappearing of the file while downloading is also fairly unusual.. Will reach out separately to take a further look at this.
