### ISSUE TITLE
Where is the archive stored?

### ISSUE THREAD

**Issue by intutest1** [webrecorder/archiveweb.page#67]
Where is the archive stored?
How do I change/specify another storage location?

**Comment by ikreymer** [comment]
The archive is stored internally in the browser itself - it is stored in the browser profile directory. It's not possible to modify this internal directory just for archiveweb.page, but you can always download the archive to export it.

**Comment by scmstr** [comment]
Hi. I don't have the space to download two terabytes onto my C drive. I don't even know where this data is being kept for now. I'm using the electron desktop app in windows - is there any way I can have this "download" the archive to a different drive (and not my OS drive)?
