### ISSUE TITLE
Usage during capture page 404 when trying to archive an unsupported protocol

### ISSUE THREAD

**Issue by av8ta** [webrecorder/archiveweb.page#86]
Hi, with the latest agregore having both ssb rendering and archiveweb.page added in extensions, I thought why not try archiving an ssb page. 

`Can't record this page.`

Which is not unexpected, but I wondered what the user would do next, so clicked the `?` icon. It directs to `https://archiveweb.page/guide/usage/during-capture.html` but the server returns 404.

![image](https://user-images.githubusercontent.com/17036768/174430902-3dd15192-d3af-435a-aa33-7c503bff121d.png)

Super excited to see both ssb rendering and webrecorder in agregore though! Great work on the initial release :)

**Comment by anisa-hawes** [comment]
Hello @av8ta. I think the page you're looking for is: https://archiveweb.page/en/usage/capture/.

Or you can explore the user guide here: https://archiveweb.page/guide

**Comment by av8ta** [comment]
Thanks @anisa-hawes I see it has been corrected here https://github.com/webrecorder/archiveweb.page/commit/3de303cad1a50e43dd61cbb372e0f6bbeb480287 so I'll close this issue.
