### ISSUE TITLE
Can't download Web Archive

### ISSUE THREAD

**Issue by yamrzou** [webrecorder/archiveweb.page#9]
First, thanks a lot for publishing this extension, it makes archiving much more straightforward.

I tried to download a Web Archive totalling 2.56 GB as a `wacz` file. The download starts but then gets stuck and the network inspector shows a stream of failing requests, as you can see in the attached screenshots.

- Downloads Tab:
![Screenshot from 2020-12-28 21-27-06](https://user-images.githubusercontent.com/40591511/103241864-beacac80-4954-11eb-912b-87ea68bc98ac.png)

- Inspect > Network:
![Screenshot from 2020-12-28 21-24-55](https://user-images.githubusercontent.com/40591511/103241875-c5d3ba80-4954-11eb-97e9-b94baee10959.png)

To see whether this is reproducible, I created a `Test` Web Archive in which I archived [https://www.google.com](https://www.google.com) and [https://twitter.com](https://twitter.com). The archive size was 5.04 MB and it downloaded correctly.

Any idea what could be causing this?

**Comment by ikreymer** [comment]
Thanks for testing, this extension is still in beta! I'll try to test it with a larger collection, 2GB+.
Serializing the WACZ requires zipping every response and also computing a hash, perhaps it is failing somewhere along the way. Can you test with download a WARC, or smaller number of pages?
I'll see if this can be fixed asap..

**Comment by yamrzou** [comment]
Thank you, I was able to download the whole archive as WARC, and successfully load it and browse its pages in [replayweb.page](https://replayweb.page)! 
That satisfies my needs for now, as I just wanted to be able to backup the archive outside the browser and load it easily.

**Comment by ikreymer** [comment]
@yamrzou Can you try the latest version (0.4.9) to see if you are able to download the 2GB+ archive now?
Made some changes that should speed up the download, and avoid buffering the entire file in memory

**Comment by yamrzou** [comment]
@ikreymer I just tried the latest version (0.4.10) from the main branch, I could download the 2GB+ WACZ successfully, thanks.

However I'm not able to load it using [replayweb.page](https://replayweb.page/). Under `Loading file://file.wacz...` an error is shown: `Unexpected Loading Error: TypeError: Assignment to constant variable.` Should I create a new issue under https://github.com/webrecorder/replayweb.page ?

**Comment by ikreymer** [comment]
Hm, I wasn't able to repro this with the large file that I tested. Would you be able to share the WACZ in some way?
You're loading the file in Chrome also, right? Hopefully this is a quick fix.

**Comment by yamrzou** [comment]
Yes I tried with both Chrome Version 89.0.4385.0  and Chromium Version 86.0.4240.111 on Fedora.

Can I have an e-mail address to send you the WACZ file? I can share it via [magic-wormhole](https://magic-wormhole.readthedocs.io/en/latest/welcome.html#installation) if you'd like. I don't want to share it publicly.

**Comment by ikreymer** [comment]
Let's try margic-wormhole! I just sent you an email to the address in your profile.

**Comment by ikreymer** [comment]
Thanks! It was a typo, now fixed and pushed. I think it should work now on replayweb.page

**Comment by yamrzou** [comment]
Indeed, it's working fine now. And the WACZ file loads much faster that WARC.
Thank you for fixing! I guess this issue can be closed now.
